var express = require('express');
var router = express.Router();

const nameList =[
  {'id': 1, 'Term': 'DevOps', 'Description': 'the DevOps approach, traditionally siloed development and operations teams work together throughout the entire software development lifecycle, from planning and coding to testing, deployment, and maintenance.' , 'References': 'Leite, L., Rocha, C., Kon, F., Milojicic, D. and Meirelles, P., 2019. A survey of DevOps concepts and challenges. ACM Computing Surveys (CSUR), 52(6), pp.1-35.'},
  {'id': 2, 'Term': 'Software engineering', 'Description': 'Software engineering is a discipline that encompasses the principles, methods, and practices used to design, develop, test, deploy, and maintain software systems.' , 'References': 'Glass, R.L., Vessey, I. and Ramesh, V., 2002. Research in software engineering: an analysis of the literature. Information and Software technology, 44(8), pp.491-506.'},
  {'id': 3, 'Term': 'Networking', 'Description': 'Computer networks refer to the interconnected systems of computers and other devices that enable communication and data exchange' , 'References': 'Peterson, L.L. and Davie, B.S., 2007. Computer networks: a systems approach. Elsevier.'},
  {'id': 4, 'Term': 'Cyber Security', 'Description': 'Cybersecurity is the practice of protecting computer systems, networks, and data from unauthorized access, use, disclosure, disruption, modification, or destruction' , 'References': 'Craigen, D., Diakun-Thibault, N. and Purse, R., 2014. Defining cybersecurity. Technology Innovation Management Review, 4(10).'},
  {'id': 5, 'Term': 'Cloud engineering', 'Description': 'Cloud engineering is a discipline that focuses on the design, development, deployment, and management of cloud-based solutions and infrastructure' , 'References': 'Harman, M., Lakhotia, K., Singer, J., White, D.R. and Yoo, S., 2013. Cloud engineering is search based software engineering too. Journal of Systems and Software, 86(9), pp.2225-2241.'},
  {'id': 6, 'Term': 'Developer', 'Description': 'It refers to the overall experience that a user has when interacting with a product, system, or service' , 'References': 'Linberg, K.R., 1999. Software developer perceptions about software project failure: a case study. Journal of systems and software, 49(2-3), pp.177-192.'},
  {'id': 7, 'Term': 'SQL developer', 'Description': 'It provides an integrated development environment (IDE) for working with SQL databases, allowing developers to interact with the database, write SQL queries, and manage database objects' , 'References': 'Narayanan, A., 2016. Oracle SQL Developer. Packt Publishing Ltd. '},
  {'id': 8, 'Term': 'Business Analyst', 'Description': 'A professional who acts as a bridge between business stakeholders and the IT team to identify, analyze, and define business needs and recommend solutions' , 'References': 'Gregorio, D.D., 2012, March. How the Business Analyst supports and encourages collaboration on agile projects. In 2012 IEEE International Systems Conference SysCon 2012 (pp. 1-4). IEEE.  '},
  {'id': 9, 'Term': 'Data Analyst', 'Description': 'A professional who collects, analyzes, and interprets large sets of data to derive meaningful insights and inform decision-making within an organization' , 'References': 'Wickham, H. and Wickham, H., 2016. Data analysis (pp. 189-201). Springer International Publishing. '},
  {'id': 10, 'Term': 'Data Scientist', 'Description': 'A professional who applies scientific methods, algorithms, and programming skills to extract knowledge and insights from complex and large datasets' , 'References': 'Davenport, T.H. and Patil, D.J., 2012. Data scientist. Harvard business review, 90(5), pp.70-76.'},
  {'id': 11, 'Term': 'Microservices', 'Description': 'Dividing application into smaller and independent services and deploying them and maintianing them seperatly ' , 'References': 'Thönes, J., 2015. Microservices. IEEE software, 32(1), pp.116-116.'},
  {'id': 12, 'Term': 'Docker', 'Description': 'A popluar tool for creating, managing  and running container it is a simplfy process and the process is containerization ' , 'References': 'Docker, I., 2020. Docker. lınea].[Junio de 2017]. Disponible en: https://www.docker.com/what-docker.'},
  {'id': 13, 'Term': 'Version Control', 'Description': 'The process of tracking and managing source code , enabling , getting code intrigrity and reverting back to previous version ' , 'References': 'Spinellis, D., 2005. Version control systems. IEEE software, 22(5), pp.108-109.'},
  {'id': 14, 'Term': 'Google Cloud ', 'Description': 'Cloud is a suite of cloud computing services provided by Google. It offers a wide range of products and solutions to help businesses and developers build, deploy, and scale applications and services in the cloud' , 'References': 'Spinellis, D., 2005. Version control systems. IEEE software, 22(5), pp.108-109.'},
  {'id': 15, 'Term': 'User Experience ', 'Description': 'It refers to overall experience and satisfaction that user has while interacting with a product, system or service or software' , 'References': 'Hassenzahl, M., 2008, September. User experience (UX) towards an experiential perspective on product quality. In Proceedings of the 20th Conference on l Interaction Homme-Machine (pp. 11-15).'},
  {'id': 16, 'Term': 'Prototype ', 'Description': 'Creating and building interactive prototype to vadidate and designing concepts full of development' , 'References': 'Galey, A. and Ruecker, S., 2010. How a prototype argues. Literary and linguistic computing, 25(4), pp.405-424.'},
  {'id': 17, 'Term': 'Deployment Pipeline ', 'Description': 'An automated sequence of steps that code changes go through, from development to production, ensuring that each step is validated before proceeding to the next.' , 'References': 'Mikita, D., DeHondt, G. and Nezlek, G.S., 2012. The deployment pipeline. In Proceedings of the Conference on Information Systems Applied Research ISSN (Vol. 2167, p. 1508)..'},
  {'id': 18, 'Term': 'Incident Management  ', 'Description': 'the process of identifying, responding to, and resolving incidents and outages in a systematic and efficient manner' , 'References': 'Runciman, W.B., Williamson, J.A.H., Deakin, A., Benveniste, K.A., Bannon, K. and Hibbert, P.D., 2006. An integrated framework for safety, quality and risk management: an information and incident management system based on a universal patient safety classification. BMJ Quality & Safety, 15(suppl 1), pp.i82-i90.'},
  {'id': 19, 'Term': 'Infrastructure as Code', 'Description': 'IaC is the practice of managing and provisioning infrastructure through code and automation tools. It allows developers to treat infrastructure configuration like code, enabling version control and reproducibility' , 'References': 'Morris, K., 2020. Infrastructure as code. O Reilly Media.'  },
  {'id': 20, 'Term': 'Orchestration ', 'Description': 'The automated management and coordination of containers or services, often provided by tools like Kubernetes and Docker Swarm.' , 'References': 'Forsyth, C., 1982. Orchestration. Courier Corporation.'},
  {'id': 21, 'Term': 'Azure', 'Description': 'Azure is cloud computing platfrom build by microsoft used for networking and machine learning','References':'Azure, M., 2016. Microsoft azure. línea]. Available: https://docs. microsoft. com/es-es/azure/virtual-machines/linux/quick-createportal.[Último acceso: 10 Diciembre 2017].'},
  {'id': 22, 'Term': 'Container', 'Description' : 'A conatiner is a lightweight and executable software package includes everything needed to run a piece of software','References':'Sofia, Z., 2000. Container technologies. Hypatia, 15(2), pp.181-201.'},
  {'id': 23, 'Term': 'Docker Compose', 'Description': 'Docker compose define and manage-container applications is particulary useful for local development', 'References':'Jangla, K. and Jangla, K., 2018. Docker compose. Accelerating Development Velocity Using Docker: Docker Across Microservices, pp.77-98.'},
  {'id': 24, 'Term': 'Incident Mangement', 'Description': 'The process of identifying , responding to and resolving incident to minimize service disruption', 'References': 'Perry, R.W., 2003. Incident management systems in disaster management. Disaster prevention and management: An international journal, 12(5), pp.405-412.'},
  {'id': 25, 'Term': 'Agile', 'Description':'A software development methodology emphasizing itervative and collaboration development', 'References':'Beck, K., Beedle, M., Van Bennekum, A., Cockburn, A., Cunningham, W., Fowler, M., Grenning, J., Highsmith, J., Hunt, A., Jeffries, R. and Kern, J., 2001. The agile manifesto.'},
  {'id': 26, 'Term': 'Capacity Planning', 'Description':'Estimating and Planning resouce requirements to meet future demand', 'References':'Green, L.V., 2004. Capacity planning and management in hospitals. Operations research and health care: A handbook of methods and applications, pp.15-41.'},
  {'id': 27, 'Term': 'Infrastructure Monitoring', 'Description':'Montioring the health and perfromance of infrastructure', 'References':'Hernantes, J., Gallardo, G. and Serrano, N., 2015. IT infrastructure-monitoring tools. IEEE software, 32(4), pp.88-93.'},
  {'id': 28, 'Term': 'Feature Flagging' , 'Description':'Gradually enable or disable feature in software using configration flag','References':'Gaskins, J., 2022. {Self-Destructing} Feature Flags.'},
  {'id': 29, 'Term': 'Data management' , 'Description':'Process of collecting storing , organising and utilizing data that add value to individual','References':'Huberman, A.M. and Miles, M.B., 1994. Data management and analysis methods.'},
  {'id': 30, 'Term': 'Data Governance', 'Description': 'It is a comprehensive framework and set of practices that ensures the effective management','References':'Al-Ruithe, M., Benkhelifa, E. and Hameed, K., 2019. A systematic literature review of data governance and cloud data governance. Personal and Ubiquitous Computing, 23, pp.839-859.'},
  {'id': 31, 'Term': 'Kubernetes', 'Description': 'Kubernetes is an open source container orchestration platform design to automate the deployment and operation of containerized applications' , 'References': 'Kubernetes, T., 2019. Kubernetes. Kubernetes. Retrieved May, 24, p.2019.'},
  {'id': 32, 'Term': 'Hybrid Cloud', 'Description': 'Kubernetes is cloud agnostic meaning it can run on various cloud providers making it suitable for hybrid deployment' , 'References': 'Weinman, J., 2016. Hybrid cloud economics. IEEE Cloud Computing, 3(1), pp.18-22.'},
  {'id': 33, 'Term': 'Rabbit MQ', 'Description': 'The open source message broker software that is widely used for building distributed and scalable' , 'References': 'Dossot, D., 2014. RabbitMQ essentials. Packt Publishing Ltd.'},
  {'id': 34, 'Term': 'Clustering ', 'Description': 'RabbitMQ can be set up in a cluster to provide high availability and fault tolerance. Clustering ensures that if one node fails, another can take over to prevent message loss.' , 'References': 'Ruspini, E.H., 1969. A new approach to clustering. Information and control, 15(1), pp.22-32.'},
  {'id': 35, 'Term': 'Terraform', 'Description': 'Terraform is an open-source infrastructure as code (IaC) tool developed by HashiCorp. It allows you to define and provision infrastructure resources, such as virtual machines, networks, databases, and more, in a declarative and version-controlled manner' , 'References': 'Zadka, M., 2022. Terraform. In DevOps in Python: Infrastructure as Python (pp. 225-230). Berkeley, CA: Apress.'},
  {'id': 36, 'Term': 'Chocolatey', 'Description': 'It is a package manager for windows that automates the process of installing, updating, configuring and removing software from a window based system' , 'References': 'Jussien, N., Rochart, G. and Lorca, X., 2008. Choco: an open source java constraint programming library. In CPAIOR08 Workshop on Open-Source Software for Integer and Contraint Programming (OSSICP08) (pp. 1-10).'},
  {'id': 37, 'Term': 'Nodemon ', 'Description': 'Nodemon is a popular utility for Node.js developers that helps automate the development workflow by monitoring changes in your Node.js applications source code and automatically restarting.' , 'References': 'Krause, J. and Krause, J., 2017. Introduction to Node. Programming Web Applications with Node, Express and Pug, pp.15-46.'},
  {'id': 38, 'Term': 'Resource group', 'Description': 'A Resource Group is a logical container within a cloud providers infrastructure where you can group together related resources for a specific application, project, or environment. It is a way to organize and manage resources in a more structured manner' , 'References': 'Rendón, D. and Rendón, D., 2022. Azure resource manager. Building Applications with Azure Resource Manager (ARM) Leverage IaC to Vastly Improve the Life Cycle of Your Applications, pp.9-17.'},
  {'id': 39, 'Term': 'Computer vision', 'Description': 'Computer vision is a multidisciplinary field of artificial intelligence (AI) and computer science that focuses on enabling computers to interpret and understand visual information from the world, much like the human visual system' , 'References': 'Forsyth, D.A. and Ponce, J., 2002. Computer vision: a modern approach. prentice hall professional technical reference.'  },
  {'id': 40, 'Term': 'HTTP ', 'Description': 'HTTP, or Hypertext Transfer Protocol, is the foundation of data communication on the World Wide Web. It is an application layer protocol used to transmit and receive data between a client and service' , 'References': 'Fielding, R., Gettys, J., Mogul, J., Frystyk, H., Masinter, L., Leach, P. and Berners-Lee, T., 1999. Hypertext transfer protocol--HTTP/1.1 (No. rfc2616).'},
]

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 DevOps Glossary', names: nameList });
});

module.exports = router;
