var express = require('express');
var router = express.Router();

const nameList =[
  {'id': 1, 'Term': 'DevOps', 'Description': 'the DevOps approach, traditionally siloed development and operations teams work together throughout the entire software development lifecycle, from planning and coding to testing, deployment, and maintenance.' , 'References': 'Leite, L., Rocha, C., Kon, F., Milojicic, D. and Meirelles, P., 2019. A survey of DevOps concepts and challenges. ACM Computing Surveys (CSUR), 52(6), pp.1-35.'},
  {'id': 2, 'Term': 'Software engineering', 'Description': 'Software engineering is a discipline that encompasses the principles, methods, and practices used to design, develop, test, deploy, and maintain software systems.' , 'References': 'Glass, R.L., Vessey, I. and Ramesh, V., 2002. Research in software engineering: an analysis of the literature. Information and Software technology, 44(8), pp.491-506.'},
  {'id': 3, 'Term': 'Networking', 'Description': 'Computer networks refer to the interconnected systems of computers and other devices that enable communication and data exchange' , 'References': 'Peterson, L.L. and Davie, B.S., 2007. Computer networks: a systems approach. Elsevier.'},
  {'id': 4, 'Term': 'Cyber Security', 'Description': 'Cybersecurity is the practice of protecting computer systems, networks, and data from unauthorized access, use, disclosure, disruption, modification, or destruction' , 'References': 'Craigen, D., Diakun-Thibault, N. and Purse, R., 2014. Defining cybersecurity. Technology Innovation Management Review, 4(10).'},
  {'id': 5, 'Term': 'Cloud engineering', 'Description': 'Cloud engineering is a discipline that focuses on the design, development, deployment, and management of cloud-based solutions and infrastructure' , 'References': 'Harman, M., Lakhotia, K., Singer, J., White, D.R. and Yoo, S., 2013. Cloud engineering is search based software engineering too. Journal of Systems and Software, 86(9), pp.2225-2241.'},
  {'id': 6, 'Term': 'Developer', 'Description': 'It refers to the overall experience that a user has when interacting with a product, system, or service' , 'References': 'Linberg, K.R., 1999. Software developer perceptions about software project failure: a case study. Journal of systems and software, 49(2-3), pp.177-192.'},
  {'id': 7, 'Term': 'SQL developer', 'Description': 'It provides an integrated development environment (IDE) for working with SQL databases, allowing developers to interact with the database, write SQL queries, and manage database objects' , 'References': 'Narayanan, A., 2016. Oracle SQL Developer. Packt Publishing Ltd. '},
  {'id': 8, 'Term': 'Business Analyst', 'Description': 'A professional who acts as a bridge between business stakeholders and the IT team to identify, analyze, and define business needs and recommend solutions' , 'References': 'Gregorio, D.D., 2012, March. How the Business Analyst supports and encourages collaboration on agile projects. In 2012 IEEE International Systems Conference SysCon 2012 (pp. 1-4). IEEE.  '},
  {'id': 9, 'Term': 'Data Analyst', 'Description': 'A professional who collects, analyzes, and interprets large sets of data to derive meaningful insights and inform decision-making within an organization' , 'References': 'Wickham, H. and Wickham, H., 2016. Data analysis (pp. 189-201). Springer International Publishing. '},
  {'id': 10, 'Term': 'Data Scientist', 'Description': 'A professional who applies scientific methods, algorithms, and programming skills to extract knowledge and insights from complex and large datasets' , 'References': 'Davenport, T.H. and Patil, D.J., 2012. Data scientist. Harvard business review, 90(5), pp.70-76.'},
  {'id': 11, 'Term': 'Microservices', 'Description': 'Dividing application into smaller and independent services and deploying them and maintianing them seperatly ' , 'References': 'Thönes, J., 2015. Microservices. IEEE software, 32(1), pp.116-116.'},
  {'id': 12, 'Term': 'Docker', 'Description': 'A popluar tool for creating, managing  and running container it is a simplfy process and the process is containerization ' , 'References': 'Docker, I., 2020. Docker. lınea].[Junio de 2017]. Disponible en: https://www. docker. com/what-docker.'},
  {'id': 13, 'Term': 'Version Control', 'Description': 'The process of tracking and managing source code , enabling , getting code intrigrity and reverting back to previous version ' , 'References': 'Spinellis, D., 2005. Version control systems. IEEE software, 22(5), pp.108-109.'},
  {'id': 14, 'Term': 'Google Cloud ', 'Description': 'Cloud is a suite of cloud computing services provided by Google. It offers a wide range of products and solutions to help businesses and developers build, deploy, and scale applications and services in the cloud' , 'References': 'Spinellis, D., 2005. Version control systems. IEEE software, 22(5), pp.108-109.'},
  {'id': 15, 'Term': 'User Experience ', 'Description': 'It refers to overall experience and satisfaction that user has while interacting with a product, system or service or software' , 'References': 'Hassenzahl, M., 2008, September. User experience (UX) towards an experiential perspective on product quality. In Proceedings of the 20th Conference on l Interaction Homme-Machine (pp. 11-15).'},
  {'id': 16, 'Term': 'Prototype ', 'Description': 'Creating and building interactive prototype to vadidate and designing concepts full of development' , 'References': 'Galey, A. and Ruecker, S., 2010. How a prototype argues. Literary and linguistic computing, 25(4), pp.405-424.'},
  {'id': 17, 'Term': 'Deployment Pipeline ', 'Description': 'An automated sequence of steps that code changes go through, from development to production, ensuring that each step is validated before proceeding to the next.' , 'References': 'Mikita, D., DeHondt, G. and Nezlek, G.S., 2012. The deployment pipeline. In Proceedings of the Conference on Information Systems Applied Research ISSN (Vol. 2167, p. 1508)..'},
  {'id': 18, 'Term': 'Incident Management  ', 'Description': 'the process of identifying, responding to, and resolving incidents and outages in a systematic and efficient manner' , 'References': 'Runciman, W.B., Williamson, J.A.H., Deakin, A., Benveniste, K.A., Bannon, K. and Hibbert, P.D., 2006. An integrated framework for safety, quality and risk management: an information and incident management system based on a universal patient safety classification. BMJ Quality & Safety, 15(suppl 1), pp.i82-i90.'},
  {'id': 19, 'Term': 'Infrastructure as Code', 'Description': 'IaC is the practice of managing and provisioning infrastructure through code and automation tools. It allows developers to treat infrastructure configuration like code, enabling version control and reproducibility' , 'References': 'Morris, K., 2020. Infrastructure as code. O Reilly Media.'  },
  {'id': 20, 'Term': 'Orchestration ', 'Description': 'The automated management and coordination of containers or services, often provided by tools like Kubernetes and Docker Swarm.' , 'References': 'Forsyth, C., 1982. Orchestration. Courier Corporation.'},

]

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 DevOps Glossary', names: nameList });
});

module.exports = router;
